### PR TITLE
biometrics: Adapt code for 12.1.0_r8 merge

### PR DESCRIPTION
**Pull request by GhostMaster69-dev**
Signed-off-by: Pranav Temkar <pranavtemkar@gmail.com>
Change-Id: Icb29b4c5aea1fe4882b64b7ba61070e9cce3f63b

### CODE REVIEW

**Comment by Darkstar085** [comment]
For..?? Why it is needed..??

**Comment by GhostMaster69-dev** [comment]
> For..?? Why it is needed..??

bootloop fix,cherry-picked from voltage.
also see proper info with crash log here: https://github.com/ArrowOS/android_frameworks_base/commit/5cff5024b8a1b9f75c282ab787d8af79a100196c

**Comment by Darkstar085** [comment]
@GhostMaster69-dev Okie

**Review by Darkstar085 — APPROVED** [review]

**Comment by GhostMaster69-dev** [comment]
> For..?? Why it is needed.. ??

basically if someone using commit https://github.com/AOSP-Silicon/android_device_xiaomi_vince/commit/e9c69a19f78835652aecd5c5b23b16c28d243115 then without this fix device boots but suddenly get into bootloop.

**Comment by GhostMaster69-dev** [comment]
> @GhostMaster69-dev Okie

okay sir

**Pull request merged**
