### PR TITLE
Revert "Camera: Prevent crash with prebuilt camera metadata"

### PR DESCRIPTION
**Pull request by dominator-prime**
This reverts commit 8b7c0d07a0a6af849844f8be964ca6d1b2e2f7ca.

* breaks portrait mode on NothingOS camera all  thanks to awsin for informing
https://github.com/PixysOS/frameworks_base/commit/be086b00d50a9774ecde8808c128c68af7ef40e2

### CODE REVIEW

**Comment by Joker-V2** [comment]
But we need it for MiuiCamera

**Comment by Darkstar085** [comment]
@Joker-V2 Lemme drop all the custom cams

**Comment by dominator-prime** [comment]
That create issues with op  NOS
If you guys want to carry  miui camera  then I'll use as vendor.sh

Don't remove camera support all peeps need that

**Comment by Darkstar085** [comment]
@optimus9811 Make a issue on issue repo plox..

**Comment by Darkstar085** [comment]
https://github.com/SuperiorOS/android_frameworks_base/commit/ad3cca82c68a3ae7de7d16af1440af5d7d9daa1f

**Pull request closed without merging**
